// Three check-your-understanding questions per lesson.
// Each: {q, options, answer (index into options), why, vi: {q, options, why}}.
// Translations sit next to the English under their language code and share the
// same answer index, so progress and scores are the same in every language.
(function (root) {
  'use strict';
  var Q = {
    'pathfinding': [
      { q: 'On a grid where every step costs the same, which algorithm finds a shortest path while exploring the fewest cells (given a good heuristic)?', options: ['DFS', 'BFS', 'A*', 'Random walk'], answer: 2, why: 'A* expands cells in order of cost-so-far + estimated cost-to-goal, so a good (admissible) heuristic steers it straight at the goal. BFS also finds a shortest path but explores in every direction.',
        vi: { q: 'Trên một lưới mà mọi bước đi có chi phí như nhau, thuật toán nào tìm được đường đi ngắn nhất mà khám phá ít ô nhất (khi có một heuristic tốt)?', options: ['DFS', 'BFS', 'A*', 'Đi ngẫu nhiên'], why: 'A* mở rộng các ô theo thứ tự chi phí đã đi + chi phí ước lượng còn lại tới đích, nên một heuristic tốt (admissible – không bao giờ ước lượng quá) sẽ lái nó thẳng về phía đích. BFS cũng tìm được đường ngắn nhất nhưng lan ra mọi hướng.' } },
      { q: 'Why can DFS return a path that is not the shortest?', options: ['It visits cells twice', 'It commits to one direction as deep as possible before trying others', 'It ignores walls', 'It only works on trees'], answer: 1, why: 'DFS follows one branch to the end before backtracking, so the first path it reaches the goal by can be long and winding.',
        vi: { q: 'Vì sao DFS có thể trả về một đường đi không phải là ngắn nhất?', options: ['Nó thăm một ô hai lần', 'Nó đi sâu hết mức theo một hướng rồi mới thử hướng khác', 'Nó bỏ qua tường', 'Nó chỉ chạy được trên cây'], why: 'DFS đi theo một nhánh đến tận cùng rồi mới quay lui, nên con đường đầu tiên đưa nó tới đích có thể dài và quanh co.' } },
      { q: 'What does Dijkstra add over BFS?', options: ['A heuristic', 'Support for different edge weights', 'Support for negative edges', 'Lower memory use'], answer: 1, why: 'Dijkstra uses a priority queue ordered by total distance, so it handles non-negative edge weights. With all weights equal it behaves like BFS.',
        vi: { q: 'Dijkstra bổ sung điều gì so với BFS?', options: ['Một heuristic', 'Hỗ trợ các cạnh có trọng số khác nhau', 'Hỗ trợ cạnh có trọng số âm', 'Dùng ít bộ nhớ hơn'], why: 'Dijkstra dùng hàng đợi ưu tiên sắp theo tổng khoảng cách, nên xử lý được trọng số cạnh không âm. Khi mọi trọng số bằng nhau, nó hoạt động giống hệt BFS.' } }
    ],
    'searching': [
      { q: 'What must be true for binary search to work?', options: ['The array is sorted', 'The array has no duplicates', 'The array length is a power of 2', 'The values are numbers'], answer: 0, why: 'Binary search discards half the range each step based on a comparison, which is only valid if the data is sorted.',
        vi: { q: 'Điều gì phải đúng thì tìm kiếm nhị phân mới hoạt động được?', options: ['Mảng đã được sắp xếp', 'Mảng không có phần tử trùng', 'Độ dài mảng là lũy thừa của 2', 'Các giá trị phải là số'], why: 'Tìm kiếm nhị phân loại bỏ một nửa khoảng ở mỗi bước dựa trên một phép so sánh, điều này chỉ hợp lệ khi dữ liệu đã được sắp xếp.' } },
      { q: 'About how many comparisons does binary search need on 1,000,000 sorted items in the worst case?', options: ['~20', '~1,000', '~500,000', '~1,000,000'], answer: 0, why: 'log₂(1,000,000) ≈ 20. Each comparison halves the remaining range.',
        vi: { q: 'Trong trường hợp xấu nhất, tìm kiếm nhị phân cần khoảng bao nhiêu phép so sánh trên 1.000.000 phần tử đã sắp xếp?', options: ['~20', '~1.000', '~500.000', '~1.000.000'], why: 'log₂(1.000.000) ≈ 20. Mỗi phép so sánh chia đôi khoảng còn lại.' } },
      { q: 'When is linear search the better choice?', options: ['Never', 'On small or unsorted data that is searched once', 'On huge sorted arrays', 'When there are duplicates'], answer: 1, why: 'Sorting costs O(n log n). For a single lookup in unsorted (or tiny) data, an O(n) scan is cheaper.',
        vi: { q: 'Khi nào tìm kiếm tuyến tính là lựa chọn tốt hơn?', options: ['Không bao giờ', 'Khi dữ liệu nhỏ hoặc chưa sắp xếp và chỉ cần tìm một lần', 'Trên mảng đã sắp xếp cực lớn', 'Khi có phần tử trùng'], why: 'Sắp xếp tốn O(n log n). Với một lần tra cứu duy nhất trên dữ liệu chưa sắp xếp (hoặc rất nhỏ), duyệt tuần tự O(n) rẻ hơn.' } }
    ],
    'sorting-comparison': [
      { q: 'Which sort has O(n log n) worst-case time AND is stable?', options: ['Quicksort', 'Merge sort', 'Heapsort', 'Selection sort'], answer: 1, why: 'Merge sort is always O(n log n) and keeps equal elements in their original order. Quicksort can degrade to O(n²); heapsort is not stable.',
        vi: { q: 'Thuật toán sắp xếp nào vừa có trường hợp xấu nhất O(n log n) VỪA ổn định (stable)?', options: ['Quicksort', 'Merge sort', 'Heapsort', 'Selection sort'], why: 'Merge sort luôn là O(n log n) và giữ nguyên thứ tự ban đầu của các phần tử bằng nhau. Quicksort có thể suy biến thành O(n²); heapsort thì không ổn định.' } },
      { q: 'What is insertion sort’s running time on an already-sorted array?', options: ['O(1)', 'O(n)', 'O(n log n)', 'O(n²)'], answer: 1, why: 'Each element is compared once with its left neighbour and stays put, so it is a single linear pass.',
        vi: { q: 'Insertion sort chạy mất bao lâu trên một mảng đã được sắp xếp sẵn?', options: ['O(1)', 'O(n)', 'O(n log n)', 'O(n²)'], why: 'Mỗi phần tử chỉ được so sánh một lần với phần tử kề bên trái rồi đứng yên tại chỗ, nên đó chỉ là một lượt duyệt tuyến tính.' } },
      { q: 'What causes quicksort’s O(n²) worst case?', options: ['Too many duplicates only', 'Pivots that repeatedly split the array very unevenly', 'Recursion depth limits', 'Using an in-place partition'], answer: 1, why: 'If the pivot is always the smallest or largest element (e.g. first-element pivot on sorted input), each partition removes just one item.',
        vi: { q: 'Điều gì gây ra trường hợp xấu nhất O(n²) của quicksort?', options: ['Chỉ do có quá nhiều phần tử trùng', 'Pivot liên tục chia mảng thành hai phần rất lệch nhau', 'Giới hạn độ sâu đệ quy', 'Dùng phân hoạch tại chỗ'], why: 'Nếu pivot luôn là phần tử nhỏ nhất hoặc lớn nhất (ví dụ chọn phần tử đầu làm pivot trên dữ liệu đã sắp xếp), mỗi lần phân hoạch chỉ loại được đúng một phần tử.' } }
    ],
    'recursion': [
      { q: 'Why is naive recursive Fibonacci so slow?', options: ['Recursion is always slow', 'It recomputes the same subproblems exponentially many times', 'It uses floating point', 'It has no base case'], answer: 1, why: 'fib(n) calls fib(n-1) and fib(n-2), which overlap heavily, giving roughly O(2ⁿ) calls. Memoization makes it O(n).',
        vi: { q: 'Vì sao Fibonacci đệ quy kiểu ngây thơ lại chậm đến vậy?', options: ['Đệ quy lúc nào cũng chậm', 'Nó tính lại cùng những bài toán con với số lần tăng theo hàm mũ', 'Nó dùng số thực dấu phẩy động', 'Nó không có trường hợp cơ sở'], why: 'fib(n) gọi fib(n-1) và fib(n-2), hai lời gọi này trùng lặp rất nhiều, dẫn tới khoảng O(2ⁿ) lời gọi. Ghi nhớ kết quả (memoization) đưa nó về O(n).' } },
      { q: 'What happens without a reachable base case?', options: ['It returns 0', 'Infinite recursion until the call stack overflows', 'It becomes iterative', 'The compiler adds one'], answer: 1, why: 'Every call pushes a new stack frame; with no stopping point the stack eventually overflows.',
        vi: { q: 'Điều gì xảy ra nếu không có trường hợp cơ sở nào chạm tới được?', options: ['Nó trả về 0', 'Đệ quy vô hạn cho đến khi tràn ngăn xếp lời gọi', 'Nó tự trở thành vòng lặp', 'Trình biên dịch tự thêm vào một trường hợp cơ sở'], why: 'Mỗi lời gọi đẩy thêm một khung (stack frame) mới vào ngăn xếp; không có điểm dừng thì sớm muộn ngăn xếp cũng bị tràn (stack overflow).' } },
      { q: 'In N-Queens backtracking, what happens when a queen can’t be placed in any column of the current row?', options: ['Restart from scratch', 'Undo the previous row’s choice and try its next column', 'Place it anyway', 'Skip the row'], answer: 1, why: 'Backtracking returns to the last decision point, undoes it, and tries the next option there.',
        vi: { q: 'Trong thuật toán quay lui N-Queens, điều gì xảy ra khi không thể đặt quân hậu vào bất kỳ cột nào của hàng hiện tại?', options: ['Bắt đầu lại từ đầu', 'Hủy lựa chọn ở hàng trước và thử cột tiếp theo của hàng đó', 'Cứ đặt vào dù vi phạm', 'Bỏ qua hàng đó'], why: 'Quay lui trở về điểm quyết định gần nhất, hủy lựa chọn ở đó và thử phương án kế tiếp.' } }
    ],
    'bitwise': [
      { q: 'What is 0b1100 XOR 0b1010?', options: ['0b1000', '0b1110', '0b0110', '0b0010'], answer: 2, why: 'XOR is 1 where the bits differ: 1100 ⊕ 1010 = 0110.',
        vi: { q: '0b1100 XOR 0b1010 bằng bao nhiêu?', options: ['0b1000', '0b1110', '0b0110', '0b0010'], why: 'XOR cho 1 ở những vị trí mà hai bit khác nhau: 1100 ⊕ 1010 = 0110.' } },
      { q: 'For a non-negative integer, what does x << 1 equal?', options: ['x / 2', 'x * 2', 'x + 1', 'x²'], answer: 1, why: 'Shifting left by one moves every bit up a place, doubling the value (as long as it doesn’t overflow).',
        vi: { q: 'Với số nguyên không âm x, x << 1 bằng gì?', options: ['x / 2', 'x * 2', 'x + 1', 'x²'], why: 'Dịch trái một vị trí đẩy mọi bit lên một bậc, làm giá trị tăng gấp đôi (miễn là không bị tràn số).' } },
      { q: 'What does x & (x - 1) == 0 test for (x > 0)?', options: ['x is even', 'x is a power of two', 'x is odd', 'x is negative'], answer: 1, why: 'A power of two has exactly one 1 bit; subtracting 1 flips it and all lower bits, so the AND is 0.',
        vi: { q: 'Biểu thức x & (x - 1) == 0 kiểm tra điều gì (với x > 0)?', options: ['x là số chẵn', 'x là lũy thừa của 2', 'x là số lẻ', 'x là số âm'], why: 'Lũy thừa của 2 có đúng một bit 1; trừ đi 1 sẽ lật bit đó cùng mọi bit thấp hơn, nên phép AND cho ra 0.' } }
    ],
    'big-number-exponentiation': [
      { q: 'How many multiplications does fast (square-and-multiply) exponentiation need for aⁿ?', options: ['O(n)', 'O(log n)', 'O(√n)', 'O(n²)'], answer: 1, why: 'Each step squares the base and halves the exponent, so it takes about log₂ n steps.',
        vi: { q: 'Lũy thừa nhanh (bình phương và nhân) cần bao nhiêu phép nhân để tính aⁿ?', options: ['O(n)', 'O(log n)', 'O(√n)', 'O(n²)'], why: 'Mỗi bước bình phương cơ số và chia đôi số mũ, nên chỉ mất khoảng log₂ n bước.' } },
      { q: 'Using square-and-multiply, how is a¹³ built? (13 = 1101 in binary)', options: ['a⁸·a⁴·a¹', 'a⁸·a⁴·a²', 'a¹⁰·a³', 'a¹²·a'], answer: 0, why: 'The 1 bits of 1101 are the 8, 4 and 1 places, so a¹³ = a⁸ · a⁴ · a¹.',
        vi: { q: 'Dùng bình phương và nhân, a¹³ được ghép lại như thế nào? (13 = 1101 ở dạng nhị phân)', options: ['a⁸·a⁴·a¹', 'a⁸·a⁴·a²', 'a¹⁰·a³', 'a¹²·a'], why: 'Các bit 1 của 1101 nằm ở vị trí 8, 4 và 1, nên a¹³ = a⁸ · a⁴ · a¹.' } },
      { q: 'Why take the modulus after every multiplication in modular exponentiation?', options: ['It is required for correctness only at the end', 'It keeps intermediate numbers small', 'It makes the result exact', 'It avoids negative numbers'], answer: 1, why: '(a·b) mod m = ((a mod m)(b mod m)) mod m, so reducing each step gives the same answer without huge intermediate values.',
        vi: { q: 'Vì sao trong lũy thừa modulo lại lấy phần dư sau mỗi phép nhân?', options: ['Chỉ cần lấy ở bước cuối là đủ để kết quả đúng', 'Để giữ cho các số trung gian luôn nhỏ', 'Để kết quả chính xác tuyệt đối', 'Để tránh số âm'], why: '(a·b) mod m = ((a mod m)(b mod m)) mod m, nên rút gọn ở mỗi bước vẫn cho cùng đáp án mà không sinh ra các giá trị trung gian khổng lồ.' } }
    ],
    'data-structures': [
      { q: 'Which structure is last-in, first-out (LIFO)?', options: ['Queue', 'Stack', 'Linked list', 'Binary search tree'], answer: 1, why: 'A stack pops the most recently pushed item first, like a stack of plates.',
        vi: { q: 'Cấu trúc nào hoạt động theo kiểu vào sau, ra trước (LIFO)?', options: ['Queue (hàng đợi)', 'Stack (ngăn xếp)', 'Danh sách liên kết', 'Cây nhị phân tìm kiếm'], why: 'Stack lấy ra phần tử được đẩy vào gần nhất trước tiên, giống như một chồng đĩa.' } },
      { q: 'What is the cost of inserting at the head of a singly linked list?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answer: 0, why: 'You create a node pointing to the old head and update the head pointer; no traversal is needed.',
        vi: { q: 'Chèn vào đầu một danh sách liên kết đơn tốn chi phí bao nhiêu?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], why: 'Bạn tạo một nút trỏ tới nút đầu cũ rồi cập nhật con trỏ head; không cần duyệt gì cả.' } },
      { q: 'An in-order traversal of a binary search tree visits keys in what order?', options: ['Insertion order', 'Sorted order', 'Reverse insertion order', 'Level by level'], answer: 1, why: 'Left subtree < node < right subtree, so left-node-right visits keys in ascending order.',
        vi: { q: 'Duyệt trung thứ tự (in-order) một cây nhị phân tìm kiếm sẽ thăm các khóa theo thứ tự nào?', options: ['Thứ tự chèn', 'Thứ tự đã sắp xếp', 'Ngược thứ tự chèn', 'Theo từng tầng'], why: 'Cây con trái < nút < cây con phải, nên thứ tự trái–nút–phải thăm các khóa theo thứ tự tăng dần.' } }
    ],
    'trie': [
      { q: 'Looking up a word of length L in a trie takes about…', options: ['O(1)', 'O(L)', 'O(log n) where n = number of words', 'O(n)'], answer: 1, why: 'You follow one edge per character, independent of how many words are stored.',
        vi: { q: 'Tra một từ có độ dài L trong trie mất khoảng…', options: ['O(1)', 'O(L)', 'O(log n) với n = số từ', 'O(n)'], why: 'Bạn đi theo đúng một cạnh cho mỗi ký tự, không phụ thuộc vào việc cây đang lưu bao nhiêu từ.' } },
      { q: 'How does a trie distinguish the word "car" from just a prefix of "card"?', options: ['It stores lengths', 'A node is flagged as end-of-word', 'It stores words in leaves only', 'It cannot'], answer: 1, why: 'Each node has an end-of-word marker; "car" is a word only if its last node is marked.',
        vi: { q: 'Làm sao trie phân biệt được từ "car" với trường hợp "car" chỉ là tiền tố của "card"?', options: ['Nó lưu độ dài từ', 'Mỗi nút có một cờ đánh dấu kết thúc từ', 'Nó chỉ lưu từ ở các lá', 'Nó không phân biệt được'], why: 'Mỗi nút có một cờ đánh dấu kết thúc từ; "car" chỉ là một từ khi nút cuối của nó được đánh dấu.' } },
      { q: 'Which task is a trie especially good at?', options: ['Finding the median', 'Autocomplete: all words with a given prefix', 'Sorting numbers', 'Shortest paths'], answer: 1, why: 'All words sharing a prefix live under the same node, so you walk to it and list its subtree.',
        vi: { q: 'Trie đặc biệt giỏi ở việc nào?', options: ['Tìm trung vị', 'Tự động hoàn thành: tìm mọi từ có chung một tiền tố cho trước', 'Sắp xếp số', 'Tìm đường đi ngắn nhất'], why: 'Mọi từ có chung một tiền tố đều nằm dưới cùng một nút, nên bạn chỉ cần đi tới nút đó rồi liệt kê cây con của nó.' } }
    ],
    'heap': [
      { q: 'In a min-heap, where is the smallest element?', options: ['A random leaf', 'The root', 'The last array slot', 'The leftmost leaf'], answer: 1, why: 'The heap property (parent ≤ children) puts the minimum at the root, index 0.',
        vi: { q: 'Trong min-heap, phần tử nhỏ nhất nằm ở đâu?', options: ['Ở một lá bất kỳ', 'Ở gốc', 'Ở ô cuối cùng của mảng', 'Ở lá ngoài cùng bên trái'], why: 'Tính chất heap (cha ≤ con) đặt giá trị nhỏ nhất ở gốc, tức chỉ số 0.' } },
      { q: 'For a node at array index i (0-based), where is its left child?', options: ['i + 1', '2i', '2i + 1', 'i / 2'], answer: 2, why: 'Children of i are at 2i+1 and 2i+2; the parent of i is at ⌊(i−1)/2⌋.',
        vi: { q: 'Với một nút ở chỉ số mảng i (đánh số từ 0), con trái của nó nằm ở đâu?', options: ['i + 1', '2i', '2i + 1', 'i / 2'], why: 'Các con của i nằm ở 2i+1 và 2i+2; cha của i nằm ở ⌊(i−1)/2⌋.' } },
      { q: 'How long does extract-min take?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 1, why: 'Move the last element to the root, then sift it down at most the tree height, which is log n.',
        vi: { q: 'Thao tác extract-min (lấy phần tử nhỏ nhất) mất bao lâu?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], why: 'Chuyển phần tử cuối lên gốc, rồi đẩy nó xuống (sift-down) tối đa bằng chiều cao của cây, tức log n.' } }
    ],
    'union-find': [
      { q: 'What does find(x) return?', options: ['The size of x’s set', 'The representative (root) of x’s set', 'All members of the set', 'x’s parent only'], answer: 1, why: 'find follows parent pointers up to the root, which identifies the set.',
        vi: { q: 'find(x) trả về gì?', options: ['Kích thước của tập chứa x', 'Phần tử đại diện (gốc) của tập chứa x', 'Mọi phần tử của tập', 'Chỉ nút cha của x'], why: 'find lần theo các con trỏ cha đi lên tới gốc, và gốc đó định danh cho cả tập.' } },
      { q: 'What does path compression do?', options: ['Deletes unused nodes', 'Points visited nodes directly at the root during find', 'Merges the two smallest sets', 'Sorts the parent array'], answer: 1, why: 'After a find, every node on the path points straight at the root, so later finds are almost O(1).',
        vi: { q: 'Nén đường đi (path compression) làm gì?', options: ['Xóa các nút không dùng tới', 'Cho các nút đã đi qua trỏ thẳng tới gốc trong lúc find', 'Hợp nhất hai tập nhỏ nhất', 'Sắp xếp mảng cha'], why: 'Sau một lần find, mọi nút trên đường đi đều trỏ thẳng tới gốc, nên các lần find sau gần như O(1).' } },
      { q: 'Union-find is the key structure in which algorithm?', options: ['Dijkstra', 'Kruskal’s minimum spanning tree', 'Binary search', 'Topological sort'], answer: 1, why: 'Kruskal adds the cheapest edge that doesn’t form a cycle; union-find checks whether both ends are already connected.',
        vi: { q: 'Union-find là cấu trúc then chốt trong thuật toán nào?', options: ['Dijkstra', 'Cây khung nhỏ nhất của Kruskal', 'Tìm kiếm nhị phân', 'Sắp xếp tô-pô'], why: 'Kruskal thêm cạnh rẻ nhất không tạo chu trình; union-find kiểm tra xem hai đầu cạnh đã được nối với nhau hay chưa.' } }
    ],
    'hashtable': [
      { q: 'What is a hash collision?', options: ['Two keys hash to the same bucket', 'A key is missing', 'The table is full', 'Two equal keys'], answer: 0, why: 'Different keys can map to the same bucket; chaining or probing handles it.',
        vi: { q: 'Xung đột băm (hash collision) là gì?', options: ['Hai khóa được băm vào cùng một bucket', 'Một khóa bị thiếu', 'Bảng đã đầy', 'Hai khóa bằng nhau'], why: 'Các khóa khác nhau có thể rơi vào cùng một bucket; nối chuỗi (chaining) hoặc dò địa chỉ (probing) sẽ xử lý chuyện này.' } },
      { q: 'Why does a hash table resize when the load factor gets high?', options: ['To sort keys', 'To keep chains short so operations stay O(1) on average', 'To free memory', 'To change the hash function'], answer: 1, why: 'More items per bucket means longer chains and slower lookups; growing the table spreads them out again.',
        vi: { q: 'Vì sao bảng băm mở rộng khi hệ số tải (load factor) tăng cao?', options: ['Để sắp xếp các khóa', 'Để giữ các chuỗi ngắn, nhờ đó các thao tác vẫn O(1) trung bình', 'Để giải phóng bộ nhớ', 'Để đổi hàm băm'], why: 'Càng nhiều phần tử trên mỗi bucket thì chuỗi càng dài và tra cứu càng chậm; mở rộng bảng sẽ dàn chúng ra lại.' } },
      { q: 'With chaining, what is the worst-case lookup time?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answer: 2, why: 'If every key lands in the same bucket, a lookup scans one chain of length n.',
        vi: { q: 'Với nối chuỗi, thời gian tra cứu trong trường hợp xấu nhất là bao nhiêu?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], why: 'Nếu mọi khóa đều rơi vào cùng một bucket, một lần tra cứu phải duyệt một chuỗi dài n.' } }
    ],
    'lru-cache': [
      { q: 'When an LRU cache is full and a new item arrives, what is evicted?', options: ['The newest item', 'The least recently used item', 'A random item', 'The largest item'], answer: 1, why: 'LRU = Least Recently Used: the item untouched for the longest time goes first.',
        vi: { q: 'Khi LRU cache đã đầy và có phần tử mới đến, phần tử nào bị loại?', options: ['Phần tử mới nhất', 'Phần tử lâu chưa được dùng nhất', 'Một phần tử ngẫu nhiên', 'Phần tử lớn nhất'], why: 'LRU = Least Recently Used: phần tử lâu nhất không được động tới sẽ bị loại trước.' } },
      { q: 'Which pair of structures gives O(1) get and put?', options: ['Array + binary search', 'Hash map + doubly linked list', 'Heap + stack', 'Trie + queue'], answer: 1, why: 'The hash map finds a node instantly; the doubly linked list moves it to the front or removes the tail in O(1).',
        vi: { q: 'Cặp cấu trúc nào cho get và put đều O(1)?', options: ['Mảng + tìm kiếm nhị phân', 'Hash map + danh sách liên kết đôi', 'Heap + stack', 'Trie + queue'], why: 'Hash map tìm ra nút ngay lập tức; danh sách liên kết đôi chuyển nút lên đầu hoặc bỏ phần tử cuối trong O(1).' } },
      { q: 'What happens to an item’s position on a successful get?', options: ['Nothing', 'It moves to the most-recently-used end', 'It is evicted', 'It moves to the least-recently-used end'], answer: 1, why: 'Reading counts as a use, so the item becomes the most recently used.',
        vi: { q: 'Vị trí của một phần tử thay đổi thế nào sau một lần get thành công?', options: ['Không thay đổi', 'Nó chuyển về phía mới dùng nhất', 'Nó bị loại', 'Nó chuyển về phía lâu chưa dùng nhất'], why: 'Đọc cũng được tính là một lần dùng, nên phần tử đó trở thành phần tử mới dùng nhất.' } }
    ],
    'segment-tree': [
      { q: 'What does a segment tree make fast?', options: ['Sorting', 'Range queries (like sum or min of a[l..r]) with point updates', 'String matching', 'Shortest paths'], answer: 1, why: 'Each node stores the answer for a segment, so any range is combined from O(log n) nodes.',
        vi: { q: 'Segment tree giúp tăng tốc việc gì?', options: ['Sắp xếp', 'Truy vấn trên khoảng (như tổng hoặc min của a[l..r]) kèm cập nhật từng điểm', 'So khớp chuỗi', 'Tìm đường đi ngắn nhất'], why: 'Mỗi nút lưu đáp án cho một đoạn, nên mọi khoảng đều được ghép từ O(log n) nút.' } },
      { q: 'Time for a range query and for a point update?', options: ['O(1) and O(n)', 'O(log n) and O(log n)', 'O(n) and O(1)', 'O(n log n) both'], answer: 1, why: 'Both walk down (or up) one root-to-leaf path plus a few siblings, about log n nodes.',
        vi: { q: 'Thời gian cho một truy vấn khoảng và cho một lần cập nhật điểm là bao nhiêu?', options: ['O(1) và O(n)', 'O(log n) và O(log n)', 'O(n) và O(1)', 'Cả hai đều O(n log n)'], why: 'Cả hai đều đi xuống (hoặc đi lên) theo một đường từ gốc tới lá, cộng thêm vài nút anh em, tức khoảng log n nút.' } },
      { q: 'Roughly how much memory does an array-based segment tree use for n elements?', options: ['n', 'up to about 4n', 'n²', 'log n'], answer: 1, why: 'A full binary tree over n leaves needs under 2n nodes when n is a power of two; 4n is the safe array size in general.',
        vi: { q: 'Segment tree cài đặt bằng mảng dùng khoảng bao nhiêu bộ nhớ cho n phần tử?', options: ['n', 'tối đa khoảng 4n', 'n²', 'log n'], why: 'Một cây nhị phân đầy đủ trên n lá cần chưa tới 2n nút khi n là lũy thừa của 2; nói chung, 4n là kích thước mảng an toàn.' } }
    ],
    'bloom-filter': [
      { q: 'A Bloom filter says "possibly in set". What can you conclude?', options: ['It is definitely in the set', 'It may be a false positive', 'It is definitely not in the set', 'The filter is full'], answer: 1, why: 'All k bits may have been set by other items, so a "yes" can be wrong.',
        vi: { q: 'Bloom filter trả lời "có thể có trong tập". Bạn kết luận được gì?', options: ['Nó chắc chắn có trong tập', 'Đó có thể là dương tính giả (false positive)', 'Nó chắc chắn không có trong tập', 'Bộ lọc đã đầy'], why: 'Cả k bit có thể đã được các phần tử khác bật lên, nên câu trả lời "có" có thể sai.' } },
      { q: 'A Bloom filter says "not in set". What can you conclude?', options: ['It might still be in the set', 'It is definitely not in the set', 'It was deleted', 'Nothing'], answer: 1, why: 'If any of the k bits is 0, the item was never added; there are no false negatives.',
        vi: { q: 'Bloom filter trả lời "không có trong tập". Bạn kết luận được gì?', options: ['Nó vẫn có thể có trong tập', 'Nó chắc chắn không có trong tập', 'Nó đã bị xóa', 'Không kết luận được gì'], why: 'Nếu bất kỳ bit nào trong k bit bằng 0 thì phần tử đó chưa từng được thêm; Bloom filter không có âm tính giả.' } },
      { q: 'Why can’t a basic Bloom filter delete items?', options: ['Bits are shared by many items, so clearing one could remove others', 'Deletion is O(n)', 'Hash functions are one-way', 'It can, easily'], answer: 0, why: 'Clearing a bit might also "remove" other items that set it, causing false negatives. Counting Bloom filters solve this.',
        vi: { q: 'Vì sao Bloom filter cơ bản không xóa được phần tử?', options: ['Các bit được nhiều phần tử dùng chung, nên tắt một bit có thể xóa luôn phần tử khác', 'Xóa tốn O(n)', 'Hàm băm là hàm một chiều', 'Có xóa được, rất dễ'], why: 'Tắt một bit có thể "xóa" luôn những phần tử khác cũng đã bật bit đó, gây ra âm tính giả. Counting Bloom filter giải quyết được vấn đề này.' } }
    ],
    'graph-algorithms': [
      { q: 'Why does Dijkstra fail with negative edge weights?', options: ['It loops forever', 'A node it finalised early could later get a shorter path', 'It needs a heuristic', 'It only works on trees'], answer: 1, why: 'Dijkstra assumes a node’s distance is final when popped; a negative edge found later could improve it. Bellman-Ford handles this.',
        vi: { q: 'Vì sao Dijkstra cho kết quả sai khi có cạnh trọng số âm?', options: ['Nó lặp vô hạn', 'Một đỉnh đã được chốt sớm về sau vẫn có thể có đường ngắn hơn', 'Nó cần một heuristic', 'Nó chỉ chạy được trên cây'], why: 'Dijkstra giả định khoảng cách của một đỉnh là cuối cùng khi nó được lấy ra; một cạnh âm phát hiện sau đó có thể cải thiện khoảng cách này. Bellman-Ford xử lý được trường hợp đó.' } },
      { q: 'A minimum spanning tree of a connected graph with V vertices has how many edges?', options: ['V', 'V − 1', 'E', '2V'], answer: 1, why: 'A tree connecting V vertices always has exactly V − 1 edges.',
        vi: { q: 'Cây khung nhỏ nhất của một đồ thị liên thông có V đỉnh có bao nhiêu cạnh?', options: ['V', 'V − 1', 'E', '2V'], why: 'Một cây nối V đỉnh luôn có đúng V − 1 cạnh.' } },
      { q: 'In what order does Kruskal consider edges?', options: ['Random', 'By increasing weight', 'By decreasing weight', 'BFS order'], answer: 1, why: 'It greedily takes the cheapest edge that doesn’t create a cycle.',
        vi: { q: 'Kruskal xét các cạnh theo thứ tự nào?', options: ['Ngẫu nhiên', 'Theo trọng số tăng dần', 'Theo trọng số giảm dần', 'Theo thứ tự BFS'], why: 'Nó chọn một cách tham lam cạnh rẻ nhất không tạo chu trình.' } }
    ],
    'topological-sort': [
      { q: 'A topological order exists only for which graphs?', options: ['Undirected graphs', 'Directed acyclic graphs (DAGs)', 'Complete graphs', 'Trees only'], answer: 1, why: 'A cycle means some task must come before itself, so no valid order exists.',
        vi: { q: 'Thứ tự tô-pô chỉ tồn tại với loại đồ thị nào?', options: ['Đồ thị vô hướng', 'Đồ thị có hướng không chu trình (DAG)', 'Đồ thị đầy đủ', 'Chỉ có cây'], why: 'Một chu trình nghĩa là có việc phải làm trước chính nó, nên không tồn tại thứ tự hợp lệ nào.' } },
      { q: 'In Kahn’s algorithm, which nodes are processed first?', options: ['Nodes with the most edges', 'Nodes with in-degree 0', 'Leaves', 'Random nodes'], answer: 1, why: 'Nodes with no incoming edges have no prerequisites, so they can go first.',
        vi: { q: 'Trong thuật toán Kahn, những đỉnh nào được xử lý trước?', options: ['Đỉnh có nhiều cạnh nhất', 'Đỉnh có bậc vào bằng 0', 'Các lá', 'Đỉnh ngẫu nhiên'], why: 'Đỉnh không có cạnh đi vào thì không có điều kiện tiên quyết, nên có thể làm trước.' } },
      { q: 'How does Kahn’s algorithm detect a cycle?', options: ['It overflows', 'Fewer than V nodes end up in the output', 'A node has in-degree 1', 'It can’t'], answer: 1, why: 'Nodes on a cycle never reach in-degree 0, so they are never output.',
        vi: { q: 'Thuật toán Kahn phát hiện chu trình bằng cách nào?', options: ['Nó bị tràn', 'Có ít hơn V đỉnh được đưa vào kết quả', 'Có một đỉnh có bậc vào bằng 1', 'Nó không phát hiện được'], why: 'Các đỉnh nằm trên chu trình không bao giờ giảm được bậc vào về 0, nên không bao giờ được đưa ra.' } }
    ],
    'consistent-hashing': [
      { q: 'What is the main benefit of consistent hashing over hash(key) mod N?', options: ['Faster hashing', 'Adding/removing a server moves only about 1/N of the keys', 'Perfect balance', 'No collisions'], answer: 1, why: 'With mod N, changing N remaps almost every key. On a ring, only keys between the changed server and its neighbour move.',
        vi: { q: 'Lợi ích chính của băm nhất quán so với hash(key) mod N là gì?', options: ['Băm nhanh hơn', 'Thêm/gỡ một server chỉ làm di chuyển khoảng 1/N số khóa', 'Cân bằng hoàn hảo', 'Không có xung đột'], why: 'Với mod N, thay đổi N sẽ ánh xạ lại gần như mọi khóa. Trên vòng băm, chỉ những khóa nằm giữa server thay đổi và server lân cận của nó mới phải di chuyển.' } },
      { q: 'Which server owns a key on the ring?', options: ['The closest server counter-clockwise', 'The first server clockwise from the key’s position', 'A random server', 'The server with fewest keys'], answer: 1, why: 'Walk clockwise from the key’s hash; the first server you meet owns it.',
        vi: { q: 'Server nào sở hữu một khóa trên vòng?', options: ['Server gần nhất theo ngược chiều kim đồng hồ', 'Server đầu tiên theo chiều kim đồng hồ tính từ vị trí của khóa', 'Một server ngẫu nhiên', 'Server đang giữ ít khóa nhất'], why: 'Đi theo chiều kim đồng hồ từ giá trị băm của khóa; server đầu tiên bạn gặp là server sở hữu nó.' } },
      { q: 'Why use virtual nodes?', options: ['To encrypt keys', 'To spread each server around the ring for better balance', 'To reduce memory', 'To avoid hashing'], answer: 1, why: 'Each physical server gets many points on the ring, smoothing out uneven gaps.',
        vi: { q: 'Vì sao lại dùng nút ảo (virtual node)?', options: ['Để mã hóa khóa', 'Để rải mỗi server ra nhiều vị trí quanh vòng, giúp cân bằng tốt hơn', 'Để giảm bộ nhớ', 'Để khỏi phải băm'], why: 'Mỗi server vật lý có nhiều điểm trên vòng, giúp san đều những khoảng trống chênh lệch.' } }
    ],
    'sliding-window': [
      { q: 'What makes sliding window O(n) instead of O(n·k)?', options: ['Sorting first', 'Updating the window result incrementally as one element enters and one leaves', 'Using recursion', 'Binary search'], answer: 1, why: 'Instead of recomputing each window from scratch, add the new element and remove the old one.',
        vi: { q: 'Điều gì khiến cửa sổ trượt chỉ tốn O(n) thay vì O(n·k)?', options: ['Sắp xếp trước', 'Cập nhật dần kết quả của cửa sổ khi một phần tử đi vào và một phần tử đi ra', 'Dùng đệ quy', 'Tìm kiếm nhị phân'], why: 'Thay vì tính lại từng cửa sổ từ đầu, chỉ cần cộng phần tử mới vào và bỏ phần tử cũ ra.' } },
      { q: 'For "longest substring without repeating characters", when does the window shrink?', options: ['Every step', 'When the new character is already in the window', 'Never', 'When the window reaches size k'], answer: 1, why: 'Move the left edge past the earlier copy of the repeated character, then continue.',
        vi: { q: 'Với bài "chuỗi con dài nhất không có ký tự lặp lại", khi nào cửa sổ thu hẹp lại?', options: ['Ở mọi bước', 'Khi ký tự mới đã có sẵn trong cửa sổ', 'Không bao giờ', 'Khi cửa sổ đạt kích thước k'], why: 'Dịch mép trái qua khỏi vị trí xuất hiện trước đó của ký tự bị lặp, rồi tiếp tục.' } },
      { q: 'Each element is added and removed at most how many times?', options: ['Once each', 'k times', 'n times', 'log n times'], answer: 0, why: 'Both edges only move forward, so every element enters once and leaves once: O(n) total.',
        vi: { q: 'Mỗi phần tử được thêm vào và lấy ra tối đa bao nhiêu lần?', options: ['Mỗi việc một lần', 'k lần', 'n lần', 'log n lần'], why: 'Cả hai mép chỉ tiến về phía trước, nên mỗi phần tử vào một lần và ra một lần: tổng cộng O(n).' } }
    ],
    'dp': [
      { q: 'Which two properties make a problem a good fit for dynamic programming?', options: ['Sorted input and small n', 'Overlapping subproblems and optimal substructure', 'Recursion and randomness', 'Greedy choice and no cycles'], answer: 1, why: 'Subproblems repeat (so caching helps) and the best answer is built from best sub-answers.',
        vi: { q: 'Hai tính chất nào khiến một bài toán phù hợp với quy hoạch động?', options: ['Dữ liệu đã sắp xếp và n nhỏ', 'Bài toán con trùng lặp và cấu trúc con tối ưu', 'Đệ quy và tính ngẫu nhiên', 'Lựa chọn tham lam và không có chu trình'], why: 'Các bài toán con lặp lại (nên lưu kết quả sẽ có lợi) và đáp án tốt nhất được ghép từ các đáp án con tốt nhất.' } },
      { q: 'Time complexity of the classic 0/1 knapsack table with n items and capacity W?', options: ['O(n)', 'O(2ⁿ)', 'O(n·W)', 'O(W)'], answer: 2, why: 'The table has n × W cells, each filled in O(1).',
        vi: { q: 'Độ phức tạp thời gian của bảng cái túi 0/1 kinh điển với n vật và sức chứa W là bao nhiêu?', options: ['O(n)', 'O(2ⁿ)', 'O(n·W)', 'O(W)'], why: 'Bảng có n × W ô, mỗi ô được điền trong O(1).' } },
      { q: 'In edit distance, what does each cell dp[i][j] represent?', options: ['Characters matched so far', 'Minimum edits to turn the first i chars of A into the first j chars of B', 'Length of the longest common substring', 'Number of insertions only'], answer: 1, why: 'Each cell takes the cheapest of insert, delete or replace from neighbouring cells.',
        vi: { q: 'Trong bài khoảng cách chỉnh sửa, mỗi ô dp[i][j] biểu diễn điều gì?', options: ['Số ký tự đã khớp đến giờ', 'Số lần sửa ít nhất để biến i ký tự đầu của A thành j ký tự đầu của B', 'Độ dài chuỗi con chung dài nhất', 'Chỉ riêng số lần chèn'], why: 'Mỗi ô lấy phương án rẻ nhất trong ba thao tác chèn, xóa hoặc thay thế, tính từ các ô lân cận.' } }
    ],
    'regex': [
      { q: 'What does the regex a* match?', options: ['Exactly one "a"', 'Zero or more "a"s', 'One or more "a"s', 'Any character'], answer: 1, why: '* means "zero or more of the previous item", so it even matches the empty string.',
        vi: { q: 'Regex a* khớp với gì?', options: ['Đúng một chữ "a"', 'Không hoặc nhiều chữ "a"', 'Một hoặc nhiều chữ "a"', 'Ký tự bất kỳ'], why: '* nghĩa là "không hoặc nhiều lần phần tử đứng trước", nên nó khớp cả chuỗi rỗng.' } },
      { q: 'What does . match (by default)?', options: ['A literal dot only', 'Any single character except a newline', 'The end of a line', 'Nothing'], answer: 1, why: 'The dot is a wildcard for one character; escape it (\\.) to match a real dot.',
        vi: { q: 'Mặc định, dấu . khớp với gì?', options: ['Chỉ một dấu chấm thật', 'Một ký tự bất kỳ, trừ ký tự xuống dòng', 'Cuối một dòng', 'Không khớp gì cả'], why: 'Dấu chấm là ký tự đại diện cho một ký tự bất kỳ; hãy escape nó (\\.) để khớp với một dấu chấm thật.' } },
      { q: 'Why can a naive backtracking regex engine be very slow on patterns like (a*)*b?', options: ['It caches too much', 'It can try exponentially many ways to split the input', 'It reads the input twice', 'Regex is always slow'], answer: 1, why: 'Nested quantifiers give many equivalent ways to match, and a failing match retries them all ("catastrophic backtracking").',
        vi: { q: 'Vì sao một bộ máy regex quay lui kiểu ngây thơ có thể cực chậm với những mẫu như (a*)*b?', options: ['Nó lưu đệm quá nhiều', 'Nó có thể thử số cách chia đầu vào tăng theo hàm mũ', 'Nó đọc đầu vào hai lần', 'Regex lúc nào cũng chậm'], why: 'Các lượng từ lồng nhau tạo ra rất nhiều cách khớp tương đương, và một lần khớp thất bại sẽ thử lại tất cả ("catastrophic backtracking" – quay lui thảm họa).' } }
    ],
    'fsm': [
      { q: 'What defines a finite state machine?', options: ['A stack and a queue', 'A finite set of states, transitions on inputs, a start state and accepting states', 'An infinite tape', 'A set of variables'], answer: 1, why: 'Those parts fully describe how the machine reacts to each input symbol.',
        vi: { q: 'Điều gì định nghĩa một máy trạng thái hữu hạn?', options: ['Một stack và một queue', 'Một tập hữu hạn các trạng thái, các phép chuyển theo đầu vào, một trạng thái bắt đầu và các trạng thái chấp nhận', 'Một băng vô hạn', 'Một tập các biến'], why: 'Những thành phần đó mô tả đầy đủ cách máy phản ứng với từng ký hiệu đầu vào.' } },
      { q: 'What is the difference between a DFA and an NFA?', options: ['DFAs can recognise more languages', 'In a DFA each state has exactly one transition per symbol; an NFA can have several or none', 'NFAs have no start state', 'There is none'], answer: 1, why: 'DFAs and NFAs recognise the same languages; an NFA can always be converted to a DFA.',
        vi: { q: 'DFA và NFA khác nhau thế nào?', options: ['DFA nhận diện được nhiều ngôn ngữ hơn', 'Trong DFA, mỗi trạng thái có đúng một phép chuyển cho mỗi ký hiệu; NFA có thể có nhiều hoặc không có', 'NFA không có trạng thái bắt đầu', 'Không khác gì cả'], why: 'DFA và NFA nhận diện cùng một lớp ngôn ngữ; NFA luôn có thể chuyển được thành DFA.' } },
      { q: 'Which can a finite state machine NOT recognise?', options: ['Binary strings with an even number of 1s', 'Strings with balanced parentheses of any depth', 'Strings ending in "ab"', 'Strings that contain "101"'], answer: 1, why: 'Arbitrary nesting needs unbounded memory (a stack); an FSM only has a fixed number of states.',
        vi: { q: 'Máy trạng thái hữu hạn KHÔNG thể nhận diện loại chuỗi nào?', options: ['Chuỗi nhị phân có số chữ số 1 là chẵn', 'Chuỗi có các dấu ngoặc cân bằng với độ sâu tùy ý', 'Chuỗi kết thúc bằng "ab"', 'Chuỗi có chứa "101"'], why: 'Lồng nhau tùy ý cần bộ nhớ không giới hạn (một stack); FSM chỉ có một số lượng trạng thái cố định.' } }
    ],
    'huffman-coding': [
      { q: 'Which symbols get the shortest Huffman codes?', options: ['The rarest', 'The most frequent', 'Alphabetically first', 'All codes are equal length'], answer: 1, why: 'Frequent symbols end up near the root, so they get fewer bits.',
        vi: { q: 'Ký hiệu nào nhận được mã Huffman ngắn nhất?', options: ['Ký hiệu hiếm nhất', 'Ký hiệu xuất hiện nhiều nhất', 'Ký hiệu đứng đầu theo bảng chữ cái', 'Mọi mã đều dài bằng nhau'], why: 'Ký hiệu xuất hiện nhiều sẽ nằm gần gốc, nên cần ít bit hơn.' } },
      { q: 'Why can Huffman codes be decoded without separators?', options: ['They are fixed length', 'No code is a prefix of another (prefix-free)', 'They use a stop bit', 'They are sorted'], answer: 1, why: 'Symbols sit only at leaves, so reading bits down the tree reaches exactly one symbol.',
        vi: { q: 'Vì sao giải mã Huffman không cần dấu phân cách?', options: ['Vì mã có độ dài cố định', 'Vì không mã nào là tiền tố của mã khác (prefix-free)', 'Vì có bit dừng', 'Vì các mã đã được sắp xếp'], why: 'Các ký hiệu chỉ nằm ở lá, nên đọc từng bit đi dần xuống cây sẽ tới đúng một ký hiệu.' } },
      { q: 'How is the Huffman tree built?', options: ['Split the alphabet in half repeatedly', 'Repeatedly merge the two least frequent nodes', 'Sort codes by length', 'Randomly'], answer: 1, why: 'A min-heap pops the two smallest weights, merges them, and pushes the sum until one tree remains.',
        vi: { q: 'Cây Huffman được dựng như thế nào?', options: ['Liên tục chia đôi bảng chữ cái', 'Liên tục gộp hai nút có tần suất thấp nhất', 'Sắp xếp các mã theo độ dài', 'Ngẫu nhiên'], why: 'Một min-heap lấy ra hai trọng số nhỏ nhất, gộp chúng lại rồi đẩy tổng vào lại, cho đến khi chỉ còn một cây.' } }
    ]
  };
  root.STUDY_LAB_QUIZZES = Q;
  if (typeof module !== 'undefined' && module.exports) module.exports = Q;
})(typeof window !== 'undefined' ? window : globalThis);
